language: java
jdk:
  - openjdk8
cache:  
  directories:  
   - $HOME/.m2  

before_install:
    - git clone --depth 1 https://github.com/kit-sdq/BuildUtilities.git /tmp/BuildUtilities
install: true

script: mvn clean verify

after_success:
- . /tmp/BuildUtilities/travis-ci/deploy.sh metamodels/demo releng/edu.kit.ipd.sdq.metamodels.demo.updatesite repository kit-sdq updatesite

notifications:
  slack:
    secure: MrgoWpjiE+pZ8EFrV6Tai4HwSuYBP3MgXeK9Ap1rBVRO1f68wbhDLQe+OMqu5ARMK5C5PYHu5Q/cY3Wmb9IGdO2h0uMnOmRkpWQNBzDP4DP96/Qxs/16rQyjf9rfMPIM6u/T1fu41HdAqqYb6QNYEBlO/0OMiBVf4PrbqbH0Bsr7DJ2decyHp/DhAPfm46qt71VABLMiTXPZcl9HR191iYIuOjdynhCntaBkjD6aDZ70Gs1LjebVZ1KM5Y9h6RnGxndePXRO94V8idOFl23Cfp8ACMh9JOWiDHX0KUkhAyTaKcN2LDuTtLXj34uxEICRcB8bfImncQkLltMh31j0WkJ35e5ymJ6W3W2jctqvvi7P8GfgJTTzYEyOFnCZ+azdChFt0PhX3nKsE0snlzpIFsXRjFSvtbogM/cPThmqaqh9Z64EzRRjS1JPRx4zos9vGczT201X0AuP8YEju0bQCKNvH5VuqdLyX5a4lZDidbTd6iTGfWvmKR+pB4ICFiXPgkPYgyY9zgjvoFNJw65J9VhQX5tupzKFTMlKF4+OOL2M8TkxBm8MN5BSPnkzu/G/37TJaPJlh2x+EQc5F964vrxCulFfjgNWYGSkbAMCR/iZXiLL4IbZk7PgZ8bXUM/FhoXk2bzkG42VZnSU9vT506E1IuP+FZ+/uMZNCTLBw+8=
